### ISSUE TITLE
English error help 

### ISSUE THREAD

**Issue by Murat1Ahmet** [KT-Yeh/Genshin-Discord-Bot#36]
Can you help me with this pls, In genshin_py/genshin_app.py Line 314, 
When i change lang to (lang="en-us") i get this error when i use /notices原神公告
how to fix.

Error is:
[05-23 20:58:49]【ERROR】@nouser#1111(611352271648718878) triggered a slash command error (CommandInvokeError)：
                　　　　Error message: Command 'notices原神公告' raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
                　　　　In components.1.components.0.options.0.description: Must be 100 or fewer in length.
                　　　　In components.2.components.0.options.2.description: Must be 100 or fewer in length.

**Comment by Lefengisbee** [comment]
Manually add a restriction to force the title and the subtitle of the notice to be equal or less than 100 words in cogs/genshin_info.py at class Notices
in here
`        def __init__(self, notices: Sequence[genshin.models.Announcement], placeholder: str):`
`            self.notices = notices`
`            options = [`
`                discord.SelectOption(label=notice.subtitle, description=notice.title, value=str(i))`
`                for i, notice in enumerate(notices)`
`            ]`
`            super().__init__(placeholder=placeholder, options=options[:25])`
change notice.subtitle to f'{notice.subtitle[:97]}...'
change notice.title to f'notice.title[:97]}...'
In that way, it will shorten the length of every notice to be equal or less than 100 words

**Comment by Lefengisbee** [comment]
If you don't want every notice to have weird "..." like this "Invoker's Secrets" Event Details..."
You can add a condition to only shorten the notices that have over 100 words in length
like this
label=f"{f'{notice.subtitle[:97]}...' if len(notice.subtitle) > 100 else notice.subtitle}"
description=f"{f'{notice.title[:97]}...' if len(notice.title) > 100 else notice.title}"

**Comment by Lefengisbee** [comment]
You have exactly pointed out the problem with the comment in your hashtag there
This issue can be solved by changing “wish” in the if condition to “Wish”. “W” must be capital.
Because of the image below, so “wish” won't work
![Screenshot_2023-05-25-07-45-22-49_572064f74bd5f9fa804b05334aa4f912](https://github.com/KT-Yeh/Genshin-Discord-Bot/assets/59505590/f5763188-5288-4b35-8fdc-db1519bbd946)

**Comment by Lefengisbee** [comment]
You have exactly pointed out the problem with the comment in your hashtag there
This issue can be solved by changing “wish” in the if condition to “Wish”. “W” must be capital.
Because of the image below, “wish” won't work
(I've made the same mistake, so I feel you)
![Screenshot_2023-05-25-07-45-22-49_572064f74bd5f9fa804b05334aa4f912](https://github.com/KT-Yeh/Genshin-Discord-Bot/assets/59505590/f5763188-5288-4b35-8fdc-db1519bbd946)
